application:
  ### Deployment values ###
  deployment:
    image:
      repository: danielyaba/python-flask
      tag: 1.0.0

    # Startup, Readiness and Liveness probes
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
      httpGet:
        path: "/"
        port: 8080
      exec: {}

    readinessProbe:
      enabled: true
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      exec:
        command:
          - cat
          - tmp/healthy

    livenessProbe:
      enabled: true
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /
        port: 8080

    # Resources to be defined for pod
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5
      requests:
        memory: 128Mi
        cpu: 0.1

  ### Ingress values ###
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: localhost:5000
        paths:
          - path: /
